# Generated by Django 5.0.2 on 2025-06-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "patients",
            "0002_patient_address_patient_allergies_patient_blood_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="visit_documents/",
                verbose_name="Ziyaret Dokümanı",
            ),
        ),
    ]
