# Generated by Django 5.0.2 on 2025-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_visit_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="contact_info",
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-posta"),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
        ),
        migrations.AddField(
            model_name="patient",
            name="tc_no",
            field=models.CharField(
                blank=True, max_length=11, verbose_name="TC Kimlik No"
            ),
        ),
    ]
