# Generated by Django 5.0.2 on 2025-06-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_remove_patient_contact_info_patient_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_code",
            field=models.CharField(
                blank=True,
                help_text="Manuel hasta kodu (opsiyonel)",
                max_length=30,
                verbose_name="Hasta Kodu",
            ),
        ),
    ]
