# Generated by Django 5.0.2 on 2025-06-16 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_visitstage_stagemedicine_stageeyeimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stageeyeimage",
            name="eye_type",
        ),
    ]
