# Generated by Django 5.0.2 on 2025-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0011_productionorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("package_requested", "Paket Hazırlama Talep Edildi"),
                    ("package_preparing", "Paket Hazırlanıyor"),
                    ("package_ready", "Paket Hazırlandı"),
                    ("production_requested", "Üretime Gönderme Talep Edildi"),
                    ("production_preparing", "Üretime Hazırlanıyor"),
                    ("production_sent", "Üretime Gönderildi"),
                    ("production_completed", "Üretim Tamamlandı"),
                    ("cargo_requested", "Kargo Hazırlama Talep Edildi"),
                    ("cargo_preparing", "Kargo Hazırlanıyor"),
                    ("cargo_ready", "Kargo Hazırlandı"),
                    ("cargo_shipped", "Kargoya Verildi"),
                    ("completed", "Tamamlandı"),
                ],
                max_length=20,
            ),
        ),
    ]
