# Generated by Django 5.0.2 on 2025-06-28 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0012_alter_productionorder_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("production_request", "Üretim Talebi"),
                            ("status_update", "Durum Güncelleme"),
                            ("production_complete", "İşlem Tamamlandı"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_user_type",
                    models.CharField(
                        choices=[
                            ("patient_manager", "Hasta Yöneticisi"),
                            ("logistic", "Lojistik"),
                        ],
                        max_length=20,
                        verbose_name="Hedef Kullanıcı Tipi",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Okundu mu?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="patients.productionorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
